# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSobastest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sobastest(self):
    self.driver.get("https://qahacking.guru/")
    self.driver.find_element(By.CSS_SELECTOR, ".uk-open:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".uk-open:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Купить").click()
    self.driver.find_element(By.NAME, "quantity[0]").click()
    self.driver.find_element(By.NAME, "quantity[0]").send_keys("10")
    self.driver.find_element(By.CSS_SELECTOR, ".cart_reload > img").click()
    self.driver.find_element(By.LINK_TEXT, "Оформить заказ").click()
    self.driver.find_element(By.NAME, "next").click()
    self.driver.find_element(By.ID, "payment_submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.ID, "agb").click()
    self.driver.find_element(By.NAME, "finish_registration").click()
  
