# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestW2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_w2(self):
    self.driver.get("https://qahacking.guru/")
    self.driver.find_element(By.CSS_SELECTOR, ".uk-open:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".uk-open:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".productitem_1 .jshop_img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-buy").click()
    self.driver.find_element(By.CSS_SELECTOR, ".even > .quantity img").click()
    self.driver.find_element(By.LINK_TEXT, "Оформить заказ").click()
  
